# Generated by Django 4.0.3 on 2022-04-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_sreg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sreg',
            table='register',
        ),
    ]
