# Generated by Django 4.0.3 on 2022-04-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_sreg_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sreg',
            table='Sreg',
        ),
    ]
